version: '3.5'
services:
  app_api_service:
    container_name: app_api
    image: asree001/stock_spring_boot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://103.207.71.135:3306/stock_spring_boot
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678

