version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: db_mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: stock_spring_boot
    networks:
      - stock_spring_boot

  phpmyadmin:
    container_name: php_my_admin
    image: phpmyadmin/phpmyadmin
    ports:
      - 7776:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_UPLOAD_MAX_SIZE: 100M
      PMA_PHP_INI_MEMORY_LIMIT: 128M
    depends_on:
      - mysql
    networks:
      - stock_spring_boot

  app_api:
    container_name: api
    image: asree001/stock_spring_boot
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - 3333:3333
    depends_on:
      - mysql
    networks:
      - stock_spring_boot
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db_mysql:3306/stock_spring_boot
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678

networks:
  stock_spring_boot:
    external: true
