version: '3.5'
services:
  app_api_service:
    container_name: app_api
    image: asree001/stock_spring_boot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    networks:
      - stock_spring_boot
networks:
  stock_spring_boot:
    external: true